CREATE TABLE IF NOT EXISTS restore_records (
    restore_record_id TEXT PRIMARY KEY,
    entity_id TEXT NOT NULL UNIQUE,
    backup_job_id TEXT NOT NULL,
    content_reference_id TEXT NOT NULL,
    file_item_id TEXT NOT NULL,
    archive_id TEXT NOT NULL,
    archive_sha256 TEXT NOT NULL,
    device_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    restore_status TEXT NOT NULL,
    restore_target_mode TEXT NOT NULL,
    conflict_strategy TEXT NOT NULL,
    archive_source TEXT NOT NULL,
    target_path TEXT NOT NULL,
    target_path_sha256 TEXT NOT NULL,
    final_path TEXT NOT NULL DEFAULT '',
    final_path_sha256 TEXT NOT NULL DEFAULT '',
    archive_path TEXT NOT NULL DEFAULT '',
    archive_path_sha256 TEXT NOT NULL DEFAULT '',
    manifest_sha256 TEXT NOT NULL DEFAULT '',
    expected_sha256 TEXT NOT NULL,
    restored_sha256 TEXT NOT NULL DEFAULT '',
    size_bytes INTEGER NOT NULL,
    restore_time TEXT,
    error_code TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    schema_version INTEGER NOT NULL,
    data_version INTEGER NOT NULL,
    revision_id TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by_device_id TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'sync_pending',
    deleted_at TEXT,
    canonical_record_sha256 TEXT NOT NULL,
    last_synced_revision_id TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(backup_job_id) REFERENCES backup_jobs(backup_job_id) ON DELETE CASCADE,
    FOREIGN KEY(content_reference_id) REFERENCES content_references(content_reference_id) ON DELETE CASCADE,
    FOREIGN KEY(file_item_id) REFERENCES file_items(file_item_id) ON DELETE CASCADE,
    FOREIGN KEY(archive_id) REFERENCES archives(archive_id) ON DELETE CASCADE,
    CHECK(size_bytes >= 0),
    CHECK(length(archive_sha256) = 64),
    CHECK(manifest_sha256 = '' OR length(manifest_sha256) = 64),
    CHECK(length(expected_sha256) = 64),
    CHECK(restored_sha256 = '' OR length(restored_sha256) = 64),
    CHECK(restore_status IN ('requested', 'restored', 'skipped_existing', 'failed')),
    CHECK(restore_target_mode IN ('original_path', 'manual_path')),
    CHECK(conflict_strategy IN ('keep_both', 'skip_existing', 'overwrite')),
    CHECK(archive_source IN ('local_cache', 'downloaded', 'not_available')),
    CHECK(sync_status IN (
        'local_committed',
        'sync_pending',
        'syncing',
        'synced',
        'sync_conflict',
        'sync_failed_retryable'
    ))
);

CREATE INDEX IF NOT EXISTS idx_restore_records_job
    ON restore_records(backup_job_id, restore_status, updated_at);

CREATE INDEX IF NOT EXISTS idx_restore_records_reference
    ON restore_records(content_reference_id, data_version);
